{
 "title": "CPAP",
 "time": { "from": "2024-02-15T12:14:30.718Z", "to": "2024-02-15T12:21:57.746Z" },
 "templating": {
  "list": [
   { "name": "flow_limit", "label": "Flow Limit", "query": "enabled, disabled" },
   { "name": "large_leak", "label": "Large Leak", "query": "enabled, disabled" },
   {
    "name": "annotations",
    "label": "Annotations",
    "query": {
     "query": "label_values(cpap_annotation,event)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Flow Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "L/s" } },
   "targets": [
    { "expr": "cpap_Flow_40ms", "legendFormat": "Flow Rate" },
    {
     "expr": "cpap_annotation{event=~\"$annotations\"}",
     "legendFormat": "{{event}}"
    },
    {
     "expr": "label_match(label_set(clamp_max(cpap_Leak_2s * 60 > 24, 1), \"label\", \"enabled\"), \"label\", \"$large_leak\")",
     "legendFormat": "Large Leak"
    },
    {
     "expr": "label_match(label_set(clamp_max(((cpap_FlowLim_2s >= 0.05) * 100), 1), \"label\", \"enabled\"), \"label\", \"$flow_limit\")",
     "legendFormat": "Flow Limit"
    }
   ]
  },
  {
   "title": "Pressure [40ms]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cm h2o" } },
   "targets": [
    { "expr": "cpap_Press_40ms", "legendFormat": "Pressure" },
    {
     "expr": "cpap_annotation{event=~\"$annotations\"}",
     "legendFormat": "{{event}}"
    },
    {
     "expr": "label_match(label_set(clamp_max(cpap_Leak_2s * 60 > 24, 1), \"label\", \"enabled\"), \"label\", \"$large_leak\")",
     "legendFormat": "Large Leak"
    },
    {
     "expr": "label_match(label_set(clamp_max(((cpap_FlowLim_2s >= 0.05) * 100), 1), \"label\", \"enabled\"), \"label\", \"$flow_limit\")",
     "legendFormat": "Flow Limit"
    }
   ]
  },
  {
   "title": "Pressure [2s]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "cm h2o" } },
   "targets": [
    { "expr": "cpap_Press_2s", "legendFormat": "Pressure" },
    {
     "expr": "cpap_annotation{event=~\"$annotations\"}",
     "legendFormat": "{{event}}"
    },
    {
     "expr": "label_match(label_set(clamp_max(cpap_Leak_2s * 60 > 24, 1), \"label\", \"enabled\"), \"label\", \"$large_leak\")",
     "legendFormat": "Large Leak"
    },
    {
     "expr": "label_match(label_set(clamp_max(((cpap_FlowLim_2s >= 0.05) * 100), 1), \"label\", \"enabled\"), \"label\", \"$flow_limit\")",
     "legendFormat": "Flow Limit"
    }
   ]
  },
  {
   "title": "AHI (incidents per hour)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(count_eq_over_time(cpap_annotation[1h], 1))",
     "legendFormat": "AHI"
    },
    {
     "expr": "cpap_annotation{event=~\"$annotations\"}",
     "legendFormat": "{{event}}"
    },
    {
     "expr": "label_match(label_set(clamp_max(cpap_Leak_2s * 60 > 24, 1), \"label\", \"enabled\"), \"label\", \"$large_leak\")",
     "legendFormat": "Large Leak"
    },
    {
     "expr": "label_match(label_set(clamp_max(((cpap_FlowLim_2s >= 0.05) * 100), 1), \"label\", \"enabled\"), \"label\", \"$flow_limit\")",
     "legendFormat": "Flow Limit"
    }
   ]
  },
  {
   "title": "Snore, Flow Limit, Leak",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "cpap_Snore_2s", "legendFormat": "Snore Index" },
    { "expr": "cpap_Leak_2s * 60", "legendFormat": "Leak Rate" },
    { "expr": "cpap_FlowLim_2s", "legendFormat": "Flow Limit." },
    {
     "expr": "cpap_annotation{event=~\"$annotations\"}",
     "legendFormat": "{{event}}"
    }
   ]
  },
  {
   "title": "Respiration Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "cpap_RespRate_2s", "legendFormat": "Respiration Rate" }
   ]
  },
  {
   "title": "Minute Vent.",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "flowlpm" } },
   "targets": [
    { "expr": "cpap_MinVent_2s", "legendFormat": "Minute Vent." }
   ]
  },
  {
   "title": "Tidal Volume",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "litre" } },
   "targets": [
    { "expr": "cpap_TidVol_2s", "legendFormat": "Tidal Volume" }
   ]
  }
 ]
}